### ISSUE TITLE
新手求助,这个错误是什么意思?

### ISSUE THREAD

**Issue by stilleshan** [Erimus-Koo/qCloud-COS-Sync#2]
[root@10-255-0-17 py]# python3 qCloud_COS_Sync.py 
Traceback (most recent call last):
  File "qCloud_COS_Sync.py", line 9, in <module>
    from qcloud_cos import *
ModuleNotFoundError: No module named 'qcloud_cos'

我已经安装过Python3和pip install -U cos-python-sdk-v5

**Comment by Erimus-Koo** [comment]
打印一下环境变量看看
```
[print(i) for i in os.sys.path]
```
看看 pip 安装的路径在不在里面。
```
pip freeze
```
可以查看路径。

再不行的话，我一时也不太确定，需要你自己排查一下原因。
[对象存储 快速入门 - SDK 文档 - 文档中心 - 腾讯云](https://cloud.tencent.com/document/product/436/12269#.E5.88.9D.E5.A7.8B.E5.8C.96)
